import Head from 'next/head'

import MyNavbar from '../components/navbar'
import SignForm from '../components/signForm'

const Signin = () => {
  return (
    <div>
      <Head>
        <title>Sign-in</title>
        <meta name="money app" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyNavbar />
      <SignForm />
    </div>
  )
}

export default Signin
