import Head from 'next/head'
import MyNavbar from '../components/navbar'

const Signup = () => {
  return (
    <div>
      <Head>
        <title>Sign-up</title>
        <meta name="money app" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyNavbar />
    </div>
  )
}

export default Signup
