import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Money app</title>
        <meta name="money app" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">plop</div>
      <button type="button" class="btn btn-primary">
        Primary
      </button>
    </div>
  );
}
