import Head from 'next/head'
import MyNavbar from '../components/navbar'

import Displayer from '../components/displayer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Money app</title>
        <meta name="money app" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyNavbar />
      <Displayer />
    </div>
  )
}
